[package]
name = "wordometer"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Joseph Wilson"]
repository = "https://..."
license = "MIT"
description = "Word counts and document statistics."
exclude = ["README.md"]
keywords = [
  
]
